### ISSUE TITLE
Sidebar styling is broken by nova-assets-changer, even without any input files

### ISSUE THREAD

**Issue by jdlien** [Muetze42/nova-assets-changer#16]
- Laravel Version: 9.19
- Nova Version: 4.11
- PHP Version: 8.1.5
- Database Driver & Version: N/A
- Operating System and Version: macOS  12.4 & Windows 10
- Browser type and version: Chrome 103

### Description:
Running php artisan nova:custom-assets seems to mess up the navigation sidebar at the left, even with no files installed in resources/Nova/Nova/.

Before:
<img width="753" alt="Screen Shot 2022-06-30 at 8 04 56 PM" src="https://user-images.githubusercontent.com/13335535/176809448-00e78c11-c7e7-4160-b87c-498f1e0afcf6.png">

After:
<img width="759" alt="Screen Shot 2022-06-30 at 8 06 12 PM" src="https://user-images.githubusercontent.com/13335535/176809465-2b15ca9d-764f-4d36-9798-d20e3b90b9ea.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
run:
php artisan nova:custom-assets.

The output contains several warnings:
```
art nova:custom-assets
Reinstall laravel/nova
  - Removing laravel/nova (4.11.1)
  - Installing laravel/nova (4.11.1): Extracting archive
Create webpack.mix.js
Run NPM install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

**Comment by Muetze42** [comment]
I reproduced it and for me it went through without errors:
https://github.com/Muetze42/nova-assets-changer/tree/issue-16-test

![image](https://user-images.githubusercontent.com/26193232/176851046-d6d4c384-27d8-4797-812f-6055f369ce30.png)

The NPM deprecated warnings come from Nova package.json directly and can be ignored. 

Have you cleared the browser cache and are you sure that the problem is not in another package?
If there is nothing in the `Nova/Nova folder`, the original Nova data is used.

**Comment by jdlien** [comment]
I thought maybe this was due to a regression or change in Nova or Nova-Assets-Changer, but this issue did begin when we switched over to Vite.

Do you think that it's possible the change to Vite would cause an issue like this? (Note that many other styles are affected besides the ones depicted in my screenshots)

**Comment by Muetze42** [comment]
So the plugin uses the assets already available from Nova. It doesn't add or change anything without you wanting it to.
If you don't change any files, the generated JS & CSS files should be identical to the ones supplied by Nova.

I'm also hearing for the first time with over 1.5k installs that there should be a problem there.
Is there an example repo somewhere with the problem?

**Comment by mateusgalasso** [comment]
Same problem here.

**Comment by Muetze42** [comment]
I can' t reproduce the error. In the projects I know it works without problems.

**Comment by mateusgalasso** [comment]
I think it's because Vite.
I removed Vite and worked.

**Comment by jdlien** [comment]
Yeah, it’s definitely Vite. But I like Vite more than I dislike the broken styling, haha.

I’m hoping for a Vite-compatible version eventually.

**Comment by Muetze42** [comment]
I would first have to see why it doesn't work with Vite. Only the Nova resources that are already there are used.

**Comment by Muetze42** [comment]
I actually experienced this error for the first time today.

In Nova's app.css the import does not happen, which is why parts were missing.
```css
@import 'nova';
@import 'fonts';
```

I couldn't find the reason for this yet, but with today's release these 2 imports are simply replaced by the content of the corresponding CSS files whereby the menu is also displayed properly with the package.

**Comment by jdlien** [comment]
Thanks for the update. Were you using Vite here?

**Comment by Muetze42** [comment]
The program executes what Nova itself delivers. In this case Mix. Just look in the folder `/vendor/laravel/nova`.

What you use for yourself does not matter, because there are 2 separate deployments.

**Comment by Muetze42** [comment]
Tested on Mac:

https://github.com/Muetze42/nova-assets-changer/releases/tag/1.2.0
