### ISSUE TITLE
README to publish login/register pages

### ISSUE THREAD

**Issue by scramatte** [Muetze42/nova-assets-changer#21]
Hello,

Can you write some README to publish login/register pages?

Regards

**Comment by Muetze42** [comment]
Yes. I make it this week

**Comment by scramatte** [comment]
Hi, 

Any news ?
I absolutely need login page with username instead email  and it looks that the old method I used doesn’t works now. 

Pleased update me.
Regards

**Comment by Muetze42** [comment]
I'm building [this registration](https://de.hf.huth.it/cp/register) in a new Laravel+Nova installation and documenting what & how I did it.

**Comment by scramatte** [comment]
I've discovered more or less how it works, but I still need some assistance. Moreover I've detected some bug in your code. Currently, all pages will be named Nova.Register( I've already made some fix for this but before PR, I need to get it full working).

<img width="521" alt="image" src="https://user-images.githubusercontent.com/188766/192097854-1c514408-d4fb-403d-b239-e3de4c84867e.png">

As you can see, I've got a couple of page, "My" and "Register" but something is missing as  path is not available, I got a 404 error when I try to access  nova/my or nova/register...

**Comment by Muetze42** [comment]
I guess the routes are missing... But is here in the manual with it.
I have not explained the content of the templates and the controllers. But it is all about Laravel & Vue Basics

https://github.com/Muetze42/nova-assets-changer/blob/main/docs/register-page.md

I also used this guide and applied it in a fresh Laravel Nova installation:

https://github.com/Muetze42/nova-assets-changer-register-page

**Comment by scramatte** [comment]
Great job! Thank you.
