### ISSUE TITLE
It looks that it's necessary to hit enter during execution of 'php artisan nova:custom-assets' ...

### ISSUE THREAD

**Issue by scramatte** [Muetze42/nova-assets-changer#23]
Hi,

It looks that it's necessary to hit enter during execution of 'php artisan nova:custom-assets'.  When reinstall Nova, may process wait user answer some question that is not displayed on screen?

Regards

**Comment by Muetze42** [comment]
Yes. When the files that are to be changed, it will ask if you want to proceed.

So you can also react after a Nova update that you may have to adjust your own files accordingly.
