### ISSUE TITLE
Overwriting views/Detail.vue

### ISSUE THREAD

**Issue by basserd** [Muetze42/nova-assets-changer#32]
**Describe the bug**
I've used the command: `php artisan custom-assests:publish` to overwrite the file `/nova/resources/js/views/Detail.vue`. This command creates a file: `resources/Nova/Nova/js/views/Detail.vue`. I'm a bit lost how this file should now replace the original file? It doesn't seem to get replaced.

**Expected behavior**
I expect the new file to be used, instead of the file within the Vendor folder.

**Comment by Muetze42** [comment]
I had somehow noticed that some changes are only applied if the command runs two times.

Please test the following:
- Run `npm run production` in the `vendor/laravel/nova` directory
- Publish the resources with `php artisan nova:publish --force` again

**Comment by basserd** [comment]
It is correct that the file is being added to:
- `resources/Nova/Nova/js/views/Detail.vue`?

Shouldn't it be:
- `resources/Nova/js/views/Detail.vue`?

But with the steps that you mentioned it still is not working.

**Comment by Muetze42** [comment]
`resources/Nova/Nova/js/views/Detail.vue` is correct.

Have You run the running command:  
`php artisan nova:custom-assets`

https://github.com/Muetze42/nova-assets-changer#running
