### ISSUE TITLE
How do I add and refer to a new component that doesn't exist in Nova? Modifying MainHeader.vue

### ISSUE THREAD

**Issue by vesper8** [Muetze42/nova-assets-changer#34]
I want to modify MainHeader.vue

I have this working if I just want to make a simple modification to it.

Specifically I want to add a `<CustomDropdown />` next to `<UserMenu />` inside `MainHeader.vue`

So I do that
```
          <div class="relative z-[40] hidden md:flex ml-2">
            <CustomDropdown />
            <UserMenu />
          </div>
```

And then inside the `<Script setup>`

I added `import CustomDropdown from '../components/CustomDropdown'`

And of course I placed a new `CustomDropdown.vue` in `resources/Nova/Nova/js/components/CustomDropdown.vue`

But when i run `php artisan nova:custom-assets` it just skips `CustomDropdown.vue` because it doesn't exist in the original ones.

I see you have a mechanism for registering new pages, but what about new components?

Am I misunderstanding how to do this?

Would love a little guidance. Many thanks!

**Comment by Muetze42** [comment]
This package add new things as page from the `New/pages` directory.

Nova itself has also become much more extensive.
You can also develop a tool and add or even override a component via the hook.
https://nova.laravel.com/docs/customization/tools.html#javascript-bootstrap-components
Have You try it?

**Comment by vesper8** [comment]
Yea I tried this technique and sometimes it works but it seems that for some components it doesn't work. I couldn't get it to work trying to override MainHeader.vue

I also kind of prefer the way you are doing it.

But I don't think we should be using `New/pages` when we want to add new components. Components are also registered differently than pages by Nova and components are auto-loaded.

I forked and made a small change to your package, you can see the new commit here: https://github.com/vesper8/nova-assets-changer/commit/247f71ad6c378eab1efde8496e540ee46a96c30a

Let me know if you would be ok with merging this PR? I also added a small convenience shortcut for rebuilding nova without reinstalling it each time.. to save time on building when developing.

**Comment by Muetze42** [comment]
New/pages is only for new pages. 

But You can register and override components as Nova Tool.

Example. Take a look to the Nova Menu by me....
https://github.com/Muetze42/nova-menu/blob/main/resources/js/tool.js

This "tool" add new components like `MenuDisclosure` and override the Nova `MainMenu` and `UserMenu`.

The Asset Changer is a cool thing, but a lot can actually be done with Nova's board tools.  
And a lot has been added to Nova in the meantime.

I started a repo with "Laravel Nova Examples" with customizing Nova without Nova Community packages. 
But unfortunately I don't have the time...

**Comment by vesper8** [comment]
Thanks @Muetze42 that's very helpful
