### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by zayedadel** [Muetze42/nova-assets-changer#4]
Can i use this package in making my nova RTL if possible please at least point out where should I start?

**Comment by Muetze42** [comment]
Nova is made with Tailwind 3. So adjusting EVERY TEMPLATE would of course be a mammoth task.

https://tailwindcss.com/blog/tailwindcss-v3#rtl-and-ltr-modifiers

I would just overwrite the Nova CSS and add RTL there.
This would also make it easier to react to Nova updates.

**Comment by zayedadel** [comment]
thank you very much! @Muetze42
